### PR TITLE
Trigger open and close events

### PR DESCRIPTION
**Pull request by danhixon**
Hi,

I needed to do something like the following so I added a couple event triggers.

$("theModal").bind('modalOpened',function(){
   // too distracting to have slideshow going in the background
   $('div.slideshow').slides('pause');
});

$("theModal").bind('modalClosed',function(){
   $('div.slideshow').slides('play');
});

### CODE REVIEW

**Comment by mkelly12** [comment]
Thanks for the patch Dan, we needed this feature in reveal. I refactored it a little to use the existing reveal:close and the new reveal:open events instead of modalOpened and modal Closed. We already had a reveal:close event that could be triggered to close the modal from your own code, made sense just to allow people to bind to that event, rather then adding another one.

**Comment by danhixon** [comment]
Cool, I really like how you refactored it!

**Comment by abergs** [comment]
How do i use the events? :)

**Comment by danhixon** [comment]
I haven't actually done it with mkelly12's refactorizations but once you have your modal set up it should be something like this:

```
$("#theModal").bind('reveal:close',function(){
  $('div.slideshow').slides('pause');
});

$("#theModal").bind('reveal:open',function(){
  $('div.slideshow').slides('play');
});
```

**Comment by abergs** [comment]
That worked, and was actually what i tried to do before asking. But i had the wrong the selector ... _doh_. Although, i have found a bug in this functoin. The event is only fired once. If i open, close and then open again the reveal:open event does not fire. Should i post this in the issues...?

**Comment by mkelly12** [comment]
Reopened to investigate @abergs comment about the open event firing only once.

Do you have some sample code I can look at Anders?

**Comment by abergs** [comment]
$("#submitModal, #raceModal").bind('reveal:open', function ()
    {
        $('.orbit-bullets').hide();
    });
    $("#submitModal").bind('reveal:close', function ()
    {
        $('.orbit-bullets').fadeIn();  
    });

The callback function only fires once...

**Comment by mkelly12** [comment]
Fixed in 918d4c29034ec68bab3b9c38e7ae29b63420c45f

**Pull request closed without merging**
