### PR TITLE
Programmatic close action

### PR DESCRIPTION
**Pull request by kendagriff**
You may object to the syntax of "closeReveal" – I didn't know if you'd prefer a separate JQuery method or not.

$('#myModal').reveal()
$('#myModal').closeReveal()

### CODE REVIEW

**Comment by kendagriff** [comment]
Also added a 'closeOnEscapeKey' option (defaulted to true).

Had a situation where I needed to prevent everything but a programmatic close event from closing the modal.

**Comment by paulbjensen** [comment]
+1. I have a small suggestion, instead of calling the function 'closeReveal', call it 'dismiss' ?

**Comment by mattdaly** [comment]
I have implemented similar functionality in my fork but using a parameter, rather than a seperate global function.

```
$('#myModal').reveal('close');
```

Implemented inside the main reveal function -

```
} else if (args === 'close') {
        return this.each(function () {
            $(this).trigger('reveal:close');
        });
    }
```

Feature list in the readme - https://github.com/mattdaly/reveal

**Comment by kendagriff** [comment]
Sweet, I like that better.

**Pull request closed without merging**
