### PR TITLE
New features

### PR DESCRIPTION
**Pull request by cobbweb**
My first pull request...

**Changes:**
- Cleaned up code. _Note: converted indentation from tabs to spaces_
- camelCased options name. _BC break_

**Features:**
- Close modal with escape key, with option closeOnEscapeKey
- onClose option, a callback function to be execute when the modal is closed

Tested on Safari 5, Chrome 10 and Firefox 4... I don't have access to IE, but changes are ultimately minimal and I don't see why they _shouldn't_ work in IE.

I could add in code for backwards compatibility with the option names.
I can switch back to tabs, but I don't like them and all my editors are set for spaces.

Is it normal to mash different things/features into one pull request?

### CODE REVIEW

**Comment by mkelly12** [comment]
Hey Andrew, there is some great stuff in here, and the code certainly needs some cleanup, but I don't think we want to change the api. The reason we did not camel case the options was because we are pulling them from data attributes, and html attributes are typically all lowercase.

As you pointed out in your comment, it's easier to merge pull requests when they are broken into smaller chunks, and do not rely on each other. I'd like to grab some of your stuff, but the options were renamed in a early commit, so the others will not apply clean.

If you still want to work on an overhaul of reveal that's great, let me know, we just need to coordinate a change this big. So that it fits with the other things we are trying to do with Reveal.

Thanks again for taking an interest in Reveal.

**Comment by cobbweb** [comment]
@mkelly
I'm think we should make it so that option names can be passed in as lowercase but use camelCased names in the actual code base, makes it much easier to read.

I've been working on a few private additions to create an alert using reveal, plus a few other small things.

What's your opinion on tabs vs. spaces? I don't mind change back to tabs if you want.

Very keen to help out where ever I can so just point me in the right direction, I'm still getting a handle on Git which is why my commit history is a bit messy... sorry about that.

If you're interested in an overhaul that's great, I've got a few other ideas which I didn't implement but maybe could factor them in.

**Comment by mkelly12** [comment]
Makes sense to use the camel cased name in the actual code base.

Spaces are fine, but reformatting changes need to be broken out as a separate commit. Otherwise it get's real tricky to see what changed functionally when all the lines are highlighted in the diff.

I'm thinking of rewriting reveal in more of a JavaScript module pattern, easier to read and mash up.
http://jqfundamentals.com/book/index.html#chapter-10

**Comment by cobbweb** [comment]
Yea I think a rewrite is good idea, I seldom pass anonymous functions directly in as callbacks. I get what you are saying about the commits, sorry for my noobiness.

**Pull request closed without merging**
